name: Java CI with Maven, thingsboard

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
- name: multiple command
  uses: appleboy/ssh-action@master
  with:
    host: ${{ secrets.HOST }}
    username: ${{ secrets.USERNAME }}
    key: ${{ secrets.KEY }}
    port: ${{ secrets.PORT }}
    script: |
      whoami
      ls -al
